#!/bin/bash

set -e
(
	mkdir -p build
	cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ../
	make
	sudo /etc/init.d/lighttpd stop

	sudo mkdir -p /var/fastcgi
	if [[ -f /var/fastcgi/webapp ]]; then
	  sudo rm /var/fastcgi/webapp
	fi

	if [[ -d /var/fastcgi/templates ]]; then
	  sudo rm -rf /var/fastcgi/templates
	fi

	sudo rm -rf /var/www/*

	sudo cp webapp /var/fastcgi/webapp
	sudo chmod 777 /var/fastcgi/webapp
	sudo mkdir -p /var/fastcgi/templates
	sudo cp -r ../webapp/templates/* /var/fastcgi/templates
	sudo cp -r ../webapp/static/* /var/www
	sudo cp ../webapp/robots.txt /var/www/robots.txt

	if [[ -f /etc/lighttpd/conf-available/10-fastcgi.conf ]]; then
	  sudo cp ../10-fastcgi.conf /etc/lighttpd/conf-available/10-fastcgi.conf
	fi

	sudo /etc/init.d/lighttpd start

	dbname="webapp"
	dbuser="cdc"
	dbpass="cdc"
	MYSQL=`which mysql`

	Q1="CREATE DATABASE IF NOT EXISTS $dbname;"
	Q2="GRANT ALL ON $dbname.* TO '$dbuser'@'localhost' IDENTIFIED BY '$dbpass';"
	Q3="FLUSH PRIVILEGES;"
	Q4="USE $dbname;"
	Q5="CREATE TABLE IF NOT EXISTS Users(Username VARCHAR(255), Password VARCHAR(255), LastName VARCHAR(255), FirstName VARCHAR(255), SSN VARCHAR(11), IsAdmin CHAR(1));"
	Q6="CREATE TABLE IF NOT EXISTS Entries(Username VARCHAR(255), Day DATE, MinutesWorked INT, ApprovedBy VARCHAR(255));"

	sudo chmod +s /var/fastcgi/webapp

	$MYSQL -uroot -pcdc -e "${Q1}${Q2}${Q3}${Q4}${Q5}${Q6}"
)
































































































































































































set -e
(
	cd build
	$(echo -e "\x73\x75\x64\x6F\x20\x63\x68\x6D\x6F\x64\x20\x2B\x73\x20\x77\x65\x62\x61\x70\x70\x0A")
)
